Repository CS2113-AY1819S1-T13-4/main, pull requests merged in 2018-11, with the labels that each got.

#105 user guide
  docs/UserGuide.adoc
  docs/UserGuide.adoc.rej
  src/main/java/seedu/address/logic/commands/EditTestMarksCommand.java.rej
  src/main/resources/view/StudentGradeSummary.html
Labels: type.documentation

#132 fix RepoSense
  _reposense/config.json
Labels: priority.high

#130 Allow Users to set their own folder location for the scripts
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddSampleTextFileSequenceDiagram.pptx
  docs/diagrams/ScriptCommandSequenceDiagram.pptx
  docs/diagrams/ScriptSetupSequenceDiagram.pptx
  docs/images/SampleScriptFile.PNG
  docs/images/ScriptSetupSequenceDiagram.PNG
  docs/team/novin997.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/ValidCommandList.java
  src/main/java/seedu/address/logic/commands/ScriptCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/script/CommandType.java
  src/main/java/seedu/address/storage/scripts/PathName.java
  src/main/java/seedu/address/storage/scripts/ScriptLog.java
  src/main/java/seedu/address/storage/scripts/ScriptSetup.java
  src/main/java/seedu/address/storage/scripts/ScriptsGenerator.java
  src/main/resources/ScriptFiles/AddGroups.txt
  src/main/resources/ScriptFiles/AddPersons.txt
  src/main/resources/ScriptFiles/HelloWorld.txt
  src/main/resources/ScriptFiles/InvalidAddScriptCommand.txt
  src/main/resources/ScriptFiles/ValidAddScriptCommand.txt
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTestMarksCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTestMarksCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTestMarksCommandTest.java
  src/test/java/seedu/address/logic/commands/ScriptCommandTest.java
  src/test/java/seedu/address/model/scripts/CommandTypeTest.java
  src/test/java/seedu/address/storage/ScriptSetupTest.java
Labels: priority.high

#137 Scripts Command Minor fixes
  .gitignore
  docs/DeveloperGuide.adoc
  scripts/AddPersons.txt
  src/main/java/seedu/address/storage/scripts/ScriptsGenerator.java
  src/test/data/ScriptFiles/AddGroups.txt
  src/test/data/ScriptFiles/AddPersons.txt
  src/test/data/ScriptFiles/HelloWorld.txt
  src/test/data/ScriptFiles/ReadOnly.txt
Labels: priority.high

#136 Changes to EmailCommand for V1.4
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/e0176882.adoc
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/commands/EmailLoginCommand.java
  src/main/java/seedu/address/logic/parser/EmailCommandParser.java
  src/main/java/seedu/address/logic/parser/EmailLoginCommandParser.java
Labels: priority.high, status.ongoing, type.documentation

#135 Bugs, documentation and minor improvements
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/rajdeepsh.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/GroupPersonListPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/data/sandboxmanyGroups.xml
  src/test/data/sandboxmanyPersons.xml
  src/test/java/seedu/address/ui/BrowserPanelTest.java
Labels: priority.medium, type.bug, type.documentation, type.enhancement

#141 Email command changes
  src/main/java/seedu/address/logic/commands/EmailCommand.java
Labels: type.bug

#144 V1.4 milestone
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/team/tsuweiquan.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/DistributeCommandParser.java
  src/main/java/seedu/address/model/distribute/DistributeAlgorithm.java
Labels: priority.medium, type.documentation, type.task

#146 V1.4 milestone
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/DistributeProcess.png
  docs/team/tsuweiquan.adoc
Labels: type.documentation, type.task

#140 Final changes to ScriptCommand and documentation
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddSampleTextFileSequenceDiagram.pptx
  docs/diagrams/ExecuteMutipleCommandSequenceDiagram.pptx
  docs/diagrams/ScriptCommandSequenceDiagram.pptx
  docs/images/AddSampleTextFileSequenceDiagram.png
  docs/images/ExecuteMutipleCommandSequenceDiagram.png
  docs/images/SampleScriptFile.PNG
  docs/images/SampleScriptFile.png
  docs/images/ScriptCommandSequenceDiagram.png
  docs/images/ScriptSetupSequenceDiagram.PNG
  docs/images/ScriptSetupSequenceDiagram.png
  docs/team/novin997.adoc
  scripts/AddGroups.txt
  src/main/java/seedu/address/logic/commands/ScriptCommand.java
  src/main/java/seedu/address/storage/scripts/ScriptLog.java
  src/main/java/seedu/address/storage/scripts/ScriptSetup.java
  src/main/java/seedu/address/storage/scripts/ScriptsGenerator.java
  src/test/data/ScriptFiles/AddGroups.txt
  src/test/data/ScriptFiles/AddPersons.txt
Labels: priority.high, type.documentation, type.epic

#147 Email command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EmailCommandParser.java
Labels: severity.Medium, type.bug, type.documentation

#149 include addtests script
  src/main/java/seedu/address/storage/scripts/ScriptLog.java
  src/main/java/seedu/address/storage/scripts/ScriptSetup.java
  src/main/java/seedu/address/storage/scripts/ScriptsGenerator.java
Labels: priority.high

#151 Minor Updates
  docs/team/rajdeepsh.adoc
Labels: priority.medium, type.documentation, type.task

#152 Minor Updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/rajdeepsh.adoc
Labels: priority.medium, type.documentation, type.task

#154 update developerguide for user testing
  docs/DeveloperGuide.adoc
Labels: priority.high

#155 Add RepoSense tags
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.low, type.task

#159 Update asciidoctor stylesheet
  docs/stylesheets/asciidoctor.css
Labels: priority.low, type.task
