Repository CS2113-AY1819S1-T13-4/main, pull requests merged in 2018-10, with the labels that each got.

#13 Added new utility to handle sending emails for new feature.
  build.gradle
  docs/AboutUs.adoc
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/commons/util/EmailUtil.java
Labels: enhancement

#18 Address Book Feature Create Group Implemented
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Group.java
  src/main/java/seedu/address/model/person/UniqueGroupList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/storage/XmlAdaptedGroup.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/AttendanceStage.java
  src/main/resources/view/AttendanceStage.fxml
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement

#20 Improve create group command
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupLocation.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/person/Group.java
  src/main/java/seedu/address/model/person/UniqueGroupList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedGroup.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
Labels: status.ongoing, type.enhancement, type.task

#23 Updated EmailCommand for V1.2
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/EmailUtil.java
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EmailCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/email/Message.java
  src/main/java/seedu/address/model/email/Subject.java
Labels: type.enhancement

#31 Add gender and nationality field into AddCommand
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DistributeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DistributeCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Nationality.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, type.enhancement

#29 calculate and sort functions for feature(grade management)
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/util/Calculator.java
  src/main/java/seedu/address/model/util/SortGrade.java
Labels: priority.high, status.ongoing

#45 manage to finish v1.2(gradesummarycommand)
  src/main/java/seedu/address/logic/commands/GradeSummaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GradeSummaryCommandParser.java
  src/main/java/seedu/address/model/util/Calculator.java
  src/main/java/seedu/address/model/util/SortGrade.java
  src/main/java/seedu/address/ui/DisplayGrade.java
  src/main/resources/view/DisplayGrade.fxml
Labels: priority.high, type.epic, type.task

#63 Update Developer Guide
  docs/DeveloperGuide.adoc
Labels: type.documentation

#65 Update dev guide with group feature implementation
  docs/DeveloperGuide.adoc
Labels: priority.low, type.documentation, type.task

#74 Script command
  .gitignore
  _reposense/config.json
  scripts/100Persons.txt
  scripts/ValidAddScriptCommand.txt
  scripts/addgroups.txt
  scripts/addpersons.txt
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ScriptCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScriptCommandParser.java
  src/main/java/seedu/address/model/script/CommandType.java
  src/main/java/seedu/address/model/script/TextFile.java
  src/test/data/ScriptCommandTest/InvalidAddScriptCommand.txt
  src/test/data/ScriptCommandTest/ValidAddScriptCommand.txt
  src/test/java/seedu/address/logic/commands/ScriptCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/scripts/CommandTypeTest.java
  src/test/java/seedu/address/model/scripts/TextFileTest.java
Labels: priority.high, status.ongoing, type.epic

#81 Distribution command v1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/DistributeUtil.java
  src/main/java/seedu/address/logic/commands/DistributeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/distribute/DistributeAlgorithm.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Nationality.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DistributeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DistributeCommandParserTest.java
  src/test/java/seedu/address/model/distribute/DistributeUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/DistributeBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.medium, type.documentation, type.enhancement

#82 Update functionalities on README.adoc
  README.adoc
Labels: priority.low, type.documentation

#84 v1.2.1 release
  README.adoc
  src/main/java/seedu/address/MainApp.java
Labels: priority.high, type.documentation

#89 Group Feature: Add student(s) to group - Undo adding of student(s) to group
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.PNG
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedGroupTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.medium, type.bug, type.enhancement

#87 Implement sending email to all Persons belonging to a Group.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SendMailSequenceDiagram.pptx
  docs/images/AliasEmailCommandGroupIndexDiagram.png
  docs/images/EmailCommandGroupIndexDiagram.png
  docs/images/EmailCommandMultipleIndexDiagram.png
  docs/images/EmailCommandSequenceDiagram.png
  docs/images/EmailCommandSingleIndexDiagram.png
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/parser/EmailCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
Labels: priority.medium, status.ongoing, type.enhancement, type.task

#88 Improvements to Script Command
  build.gradle
  docs/UserGuide.adoc
  scripts/100Persons.txt
  scripts/AddGroups.txt
  scripts/AddPersons.txt
  scripts/HelloWorld.txt
  scripts/InvalidAddScriptCommand.txt
  scripts/addpersons.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/ValidCommandList.java
  src/main/java/seedu/address/logic/commands/ScriptCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/script/CommandType.java
  src/main/java/seedu/address/storage/scripts/ScriptSetup.java
  src/test/data/ScriptFiles/AddGroups.txt
  src/test/data/ScriptFiles/AddPersons.txt
  src/test/data/ScriptFiles/HelloWorld.txt
  src/test/data/ScriptFiles/ReadOnly.txt
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/commands/ScriptCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/scripts/CommandTypeTest.java
  src/test/java/seedu/address/storage/ScriptSetupTest.java
  src/test/java/seedu/address/testutil/ScriptUtil.java
  src/test/resources/ScriptsFile/ReadOnly.txt
Labels: priority.high, severity.Medium, status.ongoing

#90 Implement Distribute by Nationality function & Fixed Undo Function for Distribute Command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DistributeSequenceDiagram.pptx
  docs/images/DistributeSequenceDiagram.png
  src/main/java/seedu/address/commons/util/DistributeUtil.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/model/distribute/DistributeAlgorithm.java
  src/test/java/seedu/address/commons/util/DistributeUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/DistributeCommandParserTest.java
  src/test/java/seedu/address/model/distribute/DistributeTest.java
  src/test/java/seedu/address/model/distribute/DistributeUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, type.bug, type.enhancement

#93 Group Feature: Select group(s) created
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/SelectGroupSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/SelectGroupSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.PNG
  docs/images/Ui.png.jpg
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/commons/events/ui/JumpToGroupListRequestEvent.java
  src/main/java/seedu/address/logic/commands/SelectGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectGroupCommandParser.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/test/java/seedu/address/logic/commands/SelectGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectGroupCommandParserTest.java
  src/test/java/seedu/address/ui/GroupListPanelTest.java
Labels: priority.high, type.documentation, type.story

#95 Developer Guide Update
  docs/DeveloperGuide.adoc
  docs/diagrams/DistributeSequenceDiagram.pptx
  docs/images/DistributeSequenceDiagram.png
  docs/images/DistributeSequenceDiagram_2.png
Labels: type.documentation, type.story

#96 Update User Guide & Dev Guide
  docs/UserGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
Labels: priority.low, type.documentation

#97 Email command test updates
  src/test/java/seedu/address/logic/commands/EmailCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
Labels: priority.high, type.task

#100 update user guide and change some format of message
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddTestMarksCommand.java
  src/main/java/seedu/address/logic/commands/AssignGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditTestMarksCommand.java
  src/main/java/seedu/address/logic/commands/GradeSummaryCommand.java
Labels: type.documentation

#101 Remove grade prefix from add instructions
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: severity.Low, type.documentation

#102 Update App version number to v1.3
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
Labels: priority.low, type.documentation
